services:
  postgres:
    image: postgres:17
    container_name: islaT_postgre
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: islaT_adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres


  game-api:
    build: ../GameApi
    container_name: islaT_game_api
    restart: unless-stopped
    environment:
      PORT: ${GAME_API_PORT}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ASSET_ADMIN_TOKEN: ${ASSET_ADMIN_TOKEN}
    ports:
      - "${GAME_API_PORT}:${GAME_API_PORT}"
    depends_on:
      - postgres

  web-server:
    build: ../WebServer
    container_name: islaT_web_server
    restart: unless-stopped
    environment:
      PORT: ${WEB_SERVER_PORT}
      GAME_API_URL: http://game-api:${GAME_API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ASSETS_DIR: /app/server_assets
    ports:
        - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    depends_on:
      - game-api
    volumes:
      - ../GameAssets/server_assets:/app/server_assets:ro  

volumes:
  postgres_data: